on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v3
          - run: pwd
          - run: ls
          - run: npm --version
          - name: 安装依赖
            run: npm install
          - name: 打包
            run: npm run build
